name = "DiffImageRotation"
uuid = "cb1f95eb-7c3a-45bc-9e18-5c07f1beaacd"
authors = ["roflmaostc <fxw+git@mailbox.org>"]
version = "0.1.0"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
